AWS SDK Update and workflow package version update
georgeboot/laravel-echo-api-gateway pull request #29
Opened 2024-08-23 18:15 UTC by michaelaguiar

2024-08-23 18:31 UTC, leob requested changes
@michaelaguiar So the main point of this PR is the `aws/aws-sdk-php` package upgrade, right? Can you explain what's the importance of this particular upgrade?

I also see that in `config/laravel-echo-api-gateway.php` a `token` property/option dropped out - that's the kind of change which I'm always a bit wary of, could we consider putting that back "just in case"?

Next step is I'd just want to pull this down and install it as part of our app on AWS/Lambda and verify that things are still working ...

2024-08-23 18:31 UTC, leob commented on config/laravel-echo-api-gateway.php
> -        'token' => env('AWS_SESSION_TOKEN'),
@michaelaguiar `token` dropped out - isn't that going to create problems? This is the kind of change that I'd be pretty wary of ...

2024-08-23 18:51 UTC, michaelaguiar commented on config/laravel-echo-api-gateway.php
> -        'token' => env('AWS_SESSION_TOKEN'),
Just added back in! 

I believe this was removed because I was having issues with the AWS SDK and this config, but let me know if it's working for you, and if not I can take a look!

Looks like everything is working when I test in Lambda

2024-08-23 19:18 UTC, leob commented on config/laravel-echo-api-gateway.php
> -        'token' => env('AWS_SESSION_TOKEN'),
> Just added back in!
> 
> I believe this was removed because I was having issues with the AWS SDK and this config, but let me know if it's working for you, and if not I can take a look!
> 
> Looks like everything is working when I test in Lambda

@michaelaguiar Thanks, I'm going to test it in our app tomorrow and if it works then I'll merge it!

2024-08-24 06:33 UTC, georgeboot commented
Probably add a editorconfig file and make sure it's adhered to. Otherwise every maintainer's ide is going to 'fix' code styling on all files.

2024-08-24 11:03 UTC, leob commented
> Probably add a editorconfig file and make sure it's adhered to. Otherwise every maintainer's ide is going to 'fix' code styling on all files.

@georgeboot Yes I noticed as well that the git diff looks "huge" just because of different indentation/formatting - I might want to have a go at quickly "fixing" that before we merge this to master ...

@michaelaguiar I'm gonna change the indentation back to the way it was before, let's try not to mess with formatting when saving a file ...

2024-08-24 14:49 UTC, michaelaguiar commented
> > Probably add a editorconfig file and make sure it's adhered to. Otherwise every maintainer's ide is going to 'fix' code styling on all files.
> 
> @georgeboot Yes I noticed as well that the git diff looks "huge" just because of different indentation/formatting - I might want to have a go at quickly "fixing" that before we merge this to master ...
> 
> @michaelaguiar I'm gonna change the indentation back to the way it was before, let's try not to mess with formatting when saving a file ...

Sorry about that! I can go head and get this fixed if you haven't started yet?

2024-08-24 14:50 UTC, leob commented
> > > Probably add a editorconfig file and make sure it's adhered to. Otherwise every maintainer's ide is going to 'fix' code styling on all files.
> > 
> > 
> > @georgeboot Yes I noticed as well that the git diff looks "huge" just because of different indentation/formatting - I might want to have a go at quickly "fixing" that before we merge this to master ...
> > @michaelaguiar I'm gonna change the indentation back to the way it was before, let's try not to mess with formatting when saving a file ...
> 
> Sorry about that! I can go head and get this fixed if you haven't started yet?

@michaelaguiar Okay yes please do, thank you!

2024-08-24 15:13 UTC, michaelaguiar commented
Ok just fixed the formatting. Looks like most of the diff now is `composer.lock`. Take a look!

I also agree with the editorconfig addition to enforce syntax styles.

2024-08-24 16:00 UTC, leob commented
@michaelaguiar I'm now checking my own fork (because I'm seeing that for our app we're still using our fork, not the main repo) and I see that in the past I also tried to upgrade `aws-sdk-php` and I deleted `token` from the config as well - because (I assume) that's what the newer SDK required ...

I tested that and it didn't work, so I reverted both changes (the SDK upgrade and also the token deletion) ... but:

- I think I tested with PHP 7 - I'm now happy to move to PHP 8
- and the SDK was a bit older, the version in your PR is bit newer

So I'm just gonna test it with this PR, and if it works for our app (with PHP 8) then we can switch our app to PHP 8, and from the fork to the main repo - that would definitely be progress!

2024-08-24 16:07 UTC, michaelaguiar commented
Yea my deployments were failing because the newer AWS SDK version expected an array instead of a string for token if I remember correctly. 

Sounds good. I believe I pulled over all changes to fix it, but let me know if you run into any issues.

2024-08-24 17:15 UTC, leob commented
> Yea my deployments were failing because the newer AWS SDK version expected an array instead of a string for token if I remember correctly.
> 
> Sounds good. I believe I pulled over all changes to fix it, but let me know if you run into any issues.

@michaelaguiar @georgeboot Woohoo, lo and behold it works, victory!

I pulled the PR down, messed a bit with our composer.json to load the dependency locally, then did an AWS/Bref deployment:

- first it complained that it needed PHP 8.1 - so I switched our Bref runtime from 7.3 to 8.1
- then it complained that the AWS SDK didn't like the "token" - so I removed the token from the config file
- and then I did a final deployment and yes BINGO it worked - and our app is now on PHP 8, which is a big win, and on a newer AWS SDK which is also nice :)

So we need to delete that "token" again (I'll do that) and then I'm gonna merge this PR !

2024-08-24 17:52 UTC, leob commented
> > Yea my deployments were failing because the newer AWS SDK version expected an array instead of a string for token if I remember correctly.
> > Sounds good. I believe I pulled over all changes to fix it, but let me know if you run into any issues.
> 
> @michaelaguiar @georgeboot Woohoo, lo and behold it works, victory!
> 
> I pulled the PR down, messed a bit with our composer.json to load the dependency locally, then did an AWS/Bref deployment:
> 
> * first it complained that it needed PHP 8.1 - so I switched our Bref runtime from 7.3 to 8.1
> * then it complained that the AWS SDK didn't like the "token" - so I removed the token from the config file
> * and then I did a final deployment and yes BINGO it worked - and our app is now on PHP 8, which is a big win, and on a newer AWS SDK which is also nice :)
> 
> So we need to delete that "token" again (I'll do that) and then I'm gonna merge this PR !

@michaelaguiar No wait lol, seems I can't make this change, because the PR branch to be merged into master is within your forked repo, can't modify it ... :)

Can you make that change please, i.e. delete the line with "token" again from `config/laravel-echo-api-gateway.php` ? Then I'll merge this PR right away, because I've already verified that it works ...

2024-08-24 18:18 UTC, michaelaguiar commented
Done!

I have one other contributor that has added some new functionality on my fork. I am going to review it and see if we want to get it merged in this repo.

2024-08-24 18:23 UTC, merged

2024-08-24 18:27 UTC, leob commented
> Done!
> 
> I have one other contributor that has added some new functionality on my fork. I am going to review it and see if we want to get it merged in this repo.

@michaelaguiar Thanks, I've merged the PR now! Yeah if the change from that collaborator looks useful then just create a PR for it and we'll check it out ...

@georgeboot Just a (probably) "dumb" question: we've now merged this PR, but do we need to increase the composer version somewhere so that people (e.g. myself, or Michael) can pull a new version of this dependency? I just assume we need to increase a version number somewhere but I'm not sure lol ... :)

2024-08-24 18:28 UTC, georgeboot commented
You need to release a new version from GitHub ;-)

2024-08-24 18:35 UTC, leob commented
> You need to release a new version from GitHub ;-)

@georgeboot Ah right, that makes sense, of course this stuff needs to go somewhere in the Composer "registry" ... you want to do that, or you want me to attempt that? By the way I saw that a couple of CI jobs were failing now, not sure if that's serious or not ...

2024-08-24 18:37 UTC, georgeboot commented
If you release on GitHub it will automatically sync to packagist.

I'll try to take a look at the CI jobs for this time.

2024-08-24 18:45 UTC, leob commented
> If you release on GitHub it will automatically sync to packagist.
> 
> I'll try to take a look at the CI jobs for this time.

@georgeboot Thanks, that might be helpful, I didn't really look at it yet, just noticed that there were errors ... can look at it next time but I'm off to bed now :)

2024-08-25 04:07 UTC, leob commented
> > If you release on GitHub it will automatically sync to packagist.
> > I'll try to take a look at the CI jobs for this time.
> 
> @georgeboot Thanks, that might be helpful, I didn't really look at it yet, just noticed that there were errors ... can look at it next time but I'm off to bed now :)
> 
> P.S. message is pretty clear, it's trying to run "pest" but that depends on a Composer plugin which is currentlty 'blocked' - question is of course if something in the PR caused this, or it was already like this before the PR :)

@michaelaguiar Looking at the git history it seems like this was originally in `composer.json` in the PR branch:

```
"allow-plugins": {
      "pestphp/pest-plugin": true
 }
 ```
 
but later on we took it out, in commit f13c2b25db077b42cfa4a8c38a5ad43020305522 ... what was the reason for that?